apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.ingressRoute.name }}
spec:
  entryPoints:
    - {{ .Values.ingressRoute.entryPoint }}
  routes:
    - match: Host(`{{ .Values.ingressRoute.host }}`)
      kind: {{ .Values.ingressRoute.kind }}
      services:
        - name: {{ .Values.ingressRoute.serviceName }}
          port: {{ .Values.ingressRoute.servicePort }}
  tls:
    certResolver: {{ .Values.ingressRoute.certResolver }}
